### ISSUE TITLE
Add service name to header

### ISSUE THREAD

**Issue by connorgurney** [alphagov/govuk-coronavirus-vulnerable-people-form#193]
Just a thought, going on the design system and service manual, but is there any intention to add the service name to the header? If so, happy to open a pull request.

**Comment by issyl0** [comment]
Thanks for the prompt! However as this is quite a short service, we decided not to include the service name in the header.

**Comment by connorgurney** [comment]
Ah, that’s fair enough. I wonder if it would be worth there being some sort of guidance in the service manual—perhaps under [naming your service](https://www.gov.uk/service-manual/design/naming-your-service)—on when/when not to show the service name?
