### ISSUE TITLE
After deadline: improve change your answers 'change links' so they're shorter

### ISSUE THREAD

**Issue by NickColley** [alphagov/govuk-coronavirus-vulnerable-people-form#46]

**Comment by injms** [comment]
This relies on a change to the component, since the component takes the question text and prepends "Change " - https://github.com/alphagov/govuk_publishing_components/blob/master/app/views/govuk_publishing_components/components/_summary_list.html.erb#L20.

**Comment by NickColley** [comment]
https://trello.com/c/y7y888Jt/91-add-custom-change-links-to-check-your-answers-page
