### ISSUE TITLE
Validation: support address, check postcode regex isnt too clever

### ISSUE THREAD

**Issue by NickColley** [alphagov/govuk-coronavirus-vulnerable-people-form#71]
It looks a bit clever, we need to make sure it doesnt restrict input by making too many assumptions about postcodes.

**Comment by huwd** [comment]
Humm this might be tough,
I remember reading this once:
https://github.com/mysociety/mapit/blob/f186a5dd13f71e63486d0ac792cd3bca8f72ebfc/mapit_gb/countries.py

**Comment by brucebolt** [comment]
When this was first implemented (for the Brexit EU Funding Form), we took the regex from https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom#Validation.

This seems to cover all formats of UK postcode, plus the BFPO addresses, non-geographic special cases and British Overseas Territories.

**Comment by huwd** [comment]
```
SPECIAL_POSTCODES = (
    'ASCN1ZZ',  # Ascension Island
    'BBND1ZZ',  # BIOT
    'BIQQ1ZZ',  # British Antarctic Territory
    'FIQQ1ZZ',  # Falkland Islands
    'PCRN1ZZ',  # Pitcairn Islands
    'SIQQ1ZZ',  # South Georgia and the South Sandwich Islands
    'STHL1ZZ',  # St Helena
    'TDCU1ZZ',  # Tristan da Cunha
    'TKCA1ZZ',  # Turks and Caicos Islands
    'GIR0AA', 'G1R0AA',  # Girobank
    'SANTA1', 'XM45HQ',  # Santa Claus
)
```

**Comment by huwd** [comment]
!? the santa claus postcode is real

**Comment by NickColley** [comment]
as long as you're confident and have used the logic elsewhere, feel free to close :)

**Comment by brucebolt** [comment]
We could probably simplify the regular expression by removing the British Overseas Territories.  If we don't already have it, we should probably have a test to check the following are all valid:

```
AA9A 9AA
A9A 9AA
A9 9AA
A99 9AA
AA9 9AA
AA99 9AA
BFPO 1
BFPO 9
```

Plus all of the above without a space.
