### ISSUE TITLE
Usability: Should the 'NHS Number' text input use a numeric keyboard?

### ISSUE THREAD

**Issue by NickColley** [alphagov/govuk-coronavirus-vulnerable-people-form#77]

**Comment by huwd** [comment]
that seems really reasonable to me!
Rails expects this to come in as a string, does anyone know what a numeric entry comes into rails as - an integer?

**Comment by NickColley** [comment]
We should use the markup here: https://design-system.service.gov.uk/components/text-input/#numbers
